server:
  port: 9527
spring:
  application:
    name: douyin-gateway
  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848 #如果用的云上托管版本，输入可访问的Nacos Server地址即可
    gateway:
      routes:
        - id: im_routh #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://douyin-im-service                #匹配后提供服务的路由地址
          predicates:
            - Path=/douyin/message/**              # 断言，路径相匹配的进行路由
#        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: lb://cloud-payment-service
#          predicates:
#            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由